"""baseline schema v1

Revision ID: 7deb519a7c1b
Revises: 
Create Date: 2026-06-07 12:27:35.055672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7deb519a7c1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('txn_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('amount_bwp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_txn_id'), 'ledger_entries', ['txn_id'], unique=False)
    op.create_table('mcc_category_map',
    sa.Column('mcc', sa.CHAR(length=4), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('mcc')
    )
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('raw_descriptor', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('mcc', sa.CHAR(length=4), nullable=True),
    sa.Column('places_id', sa.Text(), nullable=True),
    sa.Column('rail', sa.Text(), nullable=False),
    sa.Column('payout_method', sa.Text(), nullable=False),
    sa.Column('payout_ref', sa.Text(), nullable=False),
    sa.Column('settlement_policy', sa.Text(), nullable=False),
    sa.Column('commission_bps', sa.SmallInteger(), nullable=False),
    sa.Column('kyc_level', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_e164', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('kyc_level', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_e164')
    )
    op.create_table('settlement_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_bwp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('commission_bwp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_bwp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payout_status', sa.Text(), nullable=False),
    sa.Column('payout_ref', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('tap_limit_bwp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cum_tap_limit_bwp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cum_tap_spent_bwp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('barcode_secret', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('envelopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('balance_bwp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('open_to_contributions', sa.Boolean(), nullable=False),
    sa.Column('rule_set_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('balance_bwp >= 0', name='ck_envelope_nonneg'),
    sa.ForeignKeyConstraint(['rule_set_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('amount_bwp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shortfall_bwp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('txn_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_blocks',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('set_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['set_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('wallet_id', 'category')
    )
    op.create_table('wallet_members',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('wallet_id', 'person_id', 'role')
    )
    op.create_table('contribution_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('envelope_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('fixed_amount_bwp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('schedule', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['envelope_id'], ['envelopes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('envelope_categories',
    sa.Column('envelope_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['envelope_id'], ['envelopes.id'], ),
    sa.PrimaryKeyConstraint('envelope_id', 'category')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=True),
    sa.Column('envelope_id', sa.UUID(), nullable=True),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('contributor_id', sa.UUID(), nullable=True),
    sa.Column('amount_bwp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('rail', sa.Text(), nullable=False),
    sa.Column('external_ref', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('pin_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['envelope_id'], ['envelopes.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('envelope_categories')
    op.drop_table('contribution_links')
    op.drop_table('wallet_members')
    op.drop_table('wallet_blocks')
    op.drop_table('payment_requests')
    op.drop_table('envelopes')
    op.drop_table('wallets')
    op.drop_table('settlement_batches')
    op.drop_table('persons')
    op.drop_table('merchants')
    op.drop_table('mcc_category_map')
    op.drop_index(op.f('ix_ledger_entries_txn_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
